title: FarmBot Genesis Documentation
url: https://genesis.farm.bot
description: Hardware documentation and assembly instructions for FarmBot Genesis and FarmBot Genesis XL
logo: /assets/images/documentation.png
remote_theme: FarmBot-Docs/farmbot-theme@main
baseurl: /
color: '#783f04'
oldest_stable_version: 1.2
latest_version_number: 1.5
version_factor: 10.0
plugins:
  - jemoji
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jekyll-seo-tag
include:
  - _images
  - _redirects
exclude:
  - README.md
  - LICENSE
  - Gemfile
  - Gemfile.lock
  - vendor
modes:
 - internal
algolia:
  application_id: Z1MM044EZ8
  index_name: genesis
  search_only_api_key: cad8ec927860485f3a8ac1ce2372be28
  nodes_to_index: 'p,table,h1'
  max_record_size: 20000
  files_to_exclude:
    - index.md
    - /**/manufacturing/**/*
    - v0.1/**/*
    - v0.2/**/*
    - v0.3/**/*
    - v0.4/**/*
    - v0.5/**/*
    - v0.6/**/*
    - v0.7/**/*
    - v0.8/**/*
    - v0.9/**/*
    - v1.0/**/*
    - v1.1/**/*
    - v1.2/**/*
    - v1.3/**/*
    - v1.4/**/*
    - v1.6/**/*
