name: run checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: farmbot-genesis
      - uses: actions/checkout@v2
        with:
          repository: FarmBot-Docs/utilities
          path: utilities
      - uses: actions/setup-python@v2
      - run: python -m pip install -r utilities/requirements.txt
      - run: python utilities/run_all_checks.py
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: utilities/results/*
